version: '3'

services:
  sisi-salgados-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=master
      - POSTGRESQL_PASSWORD=kayrossxp
      - POSTGRESQL_DATABASE=sisisalgados
