name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy_application:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Clone Project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{secrets.SSH_USER}}
          script: |
            folder=$(ls)
            if echo $folder | grep -c ${{vars.PROJECT_NAME}}; 
            then 
              echo "projeto já clonado"
            else 
              git clone ${{vars.PROJECT_URL}};
            fi

      - name: Build Project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}

          script: |
            cd ${{vars.PROJECT_NAME}}
            git pull
            export NODE_ENV=${{vars.NODE_ENV}}
            export DATABASE_URL=${{secrets.DATABASE_URL}}
            export JWT_SECRET=${{vars.JWT_SECRET}}
            export DBUSERNAME=${{vars.DBUSERNAME}}
            export DBPASSWORD=${{vars.DBPASSWORD}}
            export DATABASE=${{vars.DATABASE}}
            docker compose config
            docker compose build --force-rm --no-cache
      
      - name: DEPLOY Project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          script: | 
            cd ${{vars.PROJECT_NAME}}
            export NODE_ENV=${{vars.NODE_ENV}}
            export DATABASE_URL=${{secrets.DATABASE_URL}}
            export JWT_SECRET=${{vars.JWT_SECRET}}
            export DBUSERNAME=${{vars.DBUSERNAME}}
            export DBPASSWORD=${{vars.DBPASSWORD}}
            export DATABASE=${{vars.DATABASE}}
            docker compose up --no-deps -d
             